<!--------------------------------------------
-- Plantilla HTML para la pagina de portada --
--------------------------------------------->
<?php /* incluimos la plantilla goblal */
include __DIR__ . '/layout.phtml' ?>
<?php /* incluimos la cabecera */
include __DIR__ . '/header.phtml' ?>
<div class="main-box">
    <div class="wrapper">
        <form action="/create-account" method="post">
            <h2 class="form-title">Crear una cuenta</h2>
            <?php
            if (isset($_SESSION['error'])) {
                foreach ($_SESSION['error'] as $error) {
                    echo "<div>$error</div>";
                }

                unset($_SESSION['error']);
            }
            ?>
            <div class="form-group">
                <input type="text" id="name" name="name" value="<?php if (isset($name)) echo $name ?>" required>
                <label for="name">Nombre y apellidos</label>
            </div>
            <div class="form-group">
                <input type="text" id="username" name="username" value="<?php if (isset($username)) echo $username?>" required>
                <label for="username">Nombre de usuario</label>
            </div>
            <div class="form-group">
                <input type="text" id="email" name="email" value="<?php if (isset($email)) echo $email?>" required>
                <label for="email">Correo electrónico</label>
            </div>
            <div class="form-group">
                <input type="password" id="password" name="password" value="<?php if (isset($password)) echo $password ?>" required>
                <label for="password">Contraseña</label>
            </div>
            <div class="form-group">
                <input type="password" id="verify" name="verify" value="<?php if (isset($verify)) echo $verify ?>" required>
                <label for="verify">Verificar contraseña</label>
            </div>
            <button class="btn">Registrarse</button>
        </form>
        <div class="aside-form">
            <p>¿Ya tienes una cuenta?</p>
            <a class="btn btn-light">Iniciar sesión</a>
        </div>
    </div>
</div>


<?php /* incluimos el footer */
include __DIR__ . '/footer.phtml' ?>