<!--------------------------------------------
-- Plantilla HTML para la pagina de portada --
--------------------------------------------->
<?php /* incluimos la plantilla goblal */
include __DIR__ . '/layout.phtml' ?>
<?php /* incluimos la cabecera */
include __DIR__ . '/header.phtml' ?>

<h1>Registrarse</h1>

<form action="/app-review/create-account" method="post">
    <?php
    if (isset($_SESSION['error'])) {
        foreach ($_SESSION['error'] as $error) {
            echo "<div>$error</div>";
        }

        unset($_SESSION['error']);
    }
    ?>
    <input type="text" name="name" placeholder="Nombre y Apellidos" value="<?php if (isset($name)) echo $name ?>" >
    <input type="text" name="username" placeholder="Nombre de usuario" value="<?php if (isset($username)) echo $username?>" >
    <input type="text" name="email" placeholder="Correo electrónico" value="<?php if (isset($email)) echo $email?>" >
    <input type="password" name="password" placeholder="Contrasela" value="<?php if (isset($password)) echo $password ?>" >
    <input type="password" name="verify" placeholder="Verificar contraseña" value="<?php if (isset($verify)) echo $verify ?>" >
    <button>Registrarse</button>
</form>


<?php /* incluimos el footer */
include __DIR__ . '/footer.phtml' ?>