<!--------------------------------------------
-- Plantilla HTML para la pagina de portada --
--------------------------------------------->
<?php /* incluimos la plantilla goblal */ include __DIR__ . '/layout.phtml' ?>
<?php /* incluimos la cabecera */ include __DIR__ . '/header.phtml' ?>

<h1>Valoraciones</h1>

<div><?php echo $product->getName() ?></div>
<form action="" method="post">
    <h4>Añadir valoracion</h4>
    <input type="hidden" name="id" value="<?php echo $review->getId() ?>">
    <select name="points">
        <option value="">Puntos</option>
        <option value="1" <?php if ($review->getPoints() == 1) echo "selected" ?>>1</option>
        <option value="2" <?php if ($review->getPoints() == 2) echo "selected" ?>>2</option>
        <option value="3" <?php if ($review->getPoints() == 3) echo "selected" ?>>3</option>
        <option value="4" <?php if ($review->getPoints() == 4) echo "selected" ?>>4</option>
        <option value="5" <?php if ($review->getPoints() == 5) echo "selected" ?>>5</option>
    </select>
    <textarea name="comment" placeholder="Comentario del producto"> <?php echo $review->getComment() ?> </textarea>

    <button type="submit">Modificar</button>

    <?php
    if (isset($_SESSION['add-error'])) {
        echo "<div>{$_SESSION['add-error']}</div>";
        unset($_SESSION['add-error']);
    }
    ?>
</form>

<?php /* incluimos el footer */ include __DIR__ . '/footer.phtml' ?>