<!--------------------------------------------
-- Plantilla HTML para la pagina de portada --
--------------------------------------------->
<?php include __DIR__ . '/layout.phtml' ?>
<?php include __DIR__ . '/header.phtml' ?>
<link rel="stylesheet" href="/public/css/admin-styles.css">
<div class="list column">
    <h2 class="list-title admin-title" style="margin: 0 auto; padding: 24px; box-sizing: border-box; width: 50%"><i class="material-icons">edit</i>Editar valoración</h2>
    <form class="edit" action="" method="post" style="margin: 16px auto">
        <div style="margin-bottom: 8px">Nombre del producto: <?php echo $product->getName() ?></div>
        <input type="hidden" name="id" value="<?php echo $review->getId() ?>">
        <input type="hidden" name="product_id" value="<?php echo $product->getId() ?>">
        <div class="form-group">
            <select name="points">
                <option value="">Puntos</option>
                <option value="1" <?php if ($review->getPoints() == 1) echo "selected" ?>>1</option>
                <option value="2" <?php if ($review->getPoints() == 2) echo "selected" ?>>2</option>
                <option value="3" <?php if ($review->getPoints() == 3) echo "selected" ?>>3</option>
                <option value="4" <?php if ($review->getPoints() == 4) echo "selected" ?>>4</option>
                <option value="5" <?php if ($review->getPoints() == 5) echo "selected" ?>>5</option>
            </select>
        </div>
        <div class="form-group">
            <textarea name="comment" placeholder="Comentario del producto"><?php echo $review->getComment() ?></textarea>
        </div>
        <button class="btn btn-light" type="submit">Modificar</button>

        <?php
        if (isset($_SESSION['msg'])) {
            echo "<div class='{$_SESSION['msg']['type']}'>{$_SESSION['msg']['msg']}</div>";
            unset($_SESSION['msg']);
        }
        ?>
    </form>
</div>

<?php include __DIR__ . '/footer.phtml' ?>