<header>
    <div class="info-bar">
        <form action="/search" method="get" class="search-box">
            <input name="args" type="text" placeholder="Buscar...">
            <i class="material-icons">search</i>
        </form>
        <div class="user-box">
<?php
if ($user) {
    echo "<div class='user-info'>
              <div class='user-info-wrapper'>
                  <div class='user-circle'>{$user->getUsername()[0]}</div>
                  <span>{$user->getUsername()}</span>
                  <i class=\"material-icons\" style=\"margin-left: 6px;vertical-align: middle;color: #707070;\">keyboard_arrow_down</i>
              </div>
              <div class='dropdown'>";
    if ($user->getRol() == 1) {
        echo     "<div class='dropdown-item'><a href='/admin/panel'>Admin Panel</a></div>";
    }
    echo         "<div class='dropdown-item'><a href='/profile'>Mi Perfil</a></div>
                  <div class='dropdown-item'><a href='/logout'>Salir</a></div>
              </div>
         </div>";
} else {
    echo "<a class='btn btn-light' href='/login'>Iniciar Sesión</a>
          <a class='btn' href='/create-account'>Registro</a>";
}
?>
        </div>
        <div class="clear"></div>
    </div>
    <nav>
        <ul>
            <li><a <?php if($uri === '/') echo "class='selected'" ?> href='/'>Inicio</a></li>
<?php
if (!isset($c['error'])) {
    foreach($c as $key => $category) {
        $parent = $category['parentInfo'];
        $children = $category['childs'];
        $selected = $uri == "/category/{$parent->getId()}" ? 'class="selected"' : '';
        echo "<li><a $selected href='/category/{$parent->getId()}'>{$parent->getName()}</a>";
        if ($children) {
            echo "<ul class='dropdown' style='height: auto;'>";
            foreach ($children as $child) {
                echo "<li class='dropdown-item'><a href='/category/{$child->getId()}'>{$child->getName()}</a></li>";
            }
            echo "</ul>";
        }
        echo "</li>";
    }
}
?>
        </ul>
    </nav>
</header>
<body>