<?php include __DIR__ . '/layout.phtml'; ?>
<?php include __DIR__ . '/header.phtml'; ?>

<h2 class="list-title"><i class="material-icons">stars</i>Lo más popular</h2>
<div class="list">

<?php if (count($populars) > 0 && !isset($populars['error'])) {
    // Iterar sobre los productos para listarlos
    foreach ($populars as $product) {
        if ($product->getNReviews() == 0) {
            $nReviews = 'Sin valoraciones';
        } elseif ($product->getNReviews() == 1) {
            $nReviews = $product->getNReviews(). ' valoración';
        } else {
            $nReviews = $product->getNReviews(). ' valoraciones';
        }
?>
    <div class='item'>
        <div class='carousel'>
    <?php if (count($product->getImg()) > 1) {
            echo "<div class='carousel__controls reverse' id='ctrl-bck-{$product->getId()}'></div >
                  <div class='carousel__controls' id='ctrl-frw-{$product->getId()}'></div >";
    } ?>
            <ul class='carousel__track' id="track-<?php echo $product->getId() ?>">
    <?php foreach ($product->getImg() as $key => $img) {
            $percent = $key * 100;
            echo "<li class='carousel__slide' style='left: $percent%'>
                    <img src='/public/img/products/{$product->getId()}/$img' height='50%' width='100%' alt='Imagen del producto'/>
                  </li>";
        }
    ?>
            </ul>
        </div>
        <h3 title="<?php echo $product->getName() ?>"><?php echo $product->getName() ?></h3>
        <a class="rating-link" href='/add-review/<?php echo$product->getId() ?>'>
            <div class="rating" title="Hacer una valoración">
                <span><?php echo number_format($product->getPoints(),1) ?></span>
                <i class='material-icons'>star</i>
            </div>
        </a>
        <a href='/list-review/<?php echo $product->getId() ?>'>(<?php echo $nReviews ?>)</a>
        <div class="look">
            <a>Ver más</a>
        </div>
    </div>
<?php
    }
} else {
    echo $populars['error'];
}
?>
</div>

<h2><i class="material-icons">label</i>Lo más nuevo</h2>
<div class="list">
<?php if (count($new) > 0 && !isset($new['error'])) {
    // Iterar sobre los productos para listarlos
    foreach ($new as $product) {
        if ($product->getNReviews() == 0) {
            $nReviews = 'Sin valoraciones';
        } elseif ($product->getNReviews() == 1) {
            $nReviews = $product->getNReviews(). ' valoración';
        } else {
            $nReviews = $product->getNReviews(). ' valoraciones';
        }
        ?>
        <div class='item'>
            <div class='carousel'>
                <?php if (count($product->getImg()) > 1) {
                    echo "<div class='carousel__controls reverse' id='ctrl-bck-{$product->getId()}'></div >
              <div class='carousel__controls' id='ctrl-frw-{$product->getId()}'></div >";
                } ?>
                <ul class='carousel__track' id="track-<?php echo $product->getId() ?>">
                    <?php foreach ($product->getImg() as $key => $img) {
                        $percent = $key * 100;
                        echo "<li class='carousel__slide' style='left: $percent%'>
                <img src='./public/img/products/{$product->getId()}/$img' height='50%' width='100%' alt='Imagen del producto'/>
              </li>";
                    }
                    ?>
                </ul>
            </div>
            <h3 title="<?php echo $product->getName() ?>"><?php echo $product->getName() ?></h3>
            <a class="rating-link" href='/add-review/<?php echo$product->getId() ?>'>
                <div class="rating" title="Hacer una valoración">
                    <span><?php echo $product->getPoints() ?></span>
                    <i class='material-icons'>star</i>
                </div>
            </a>
            <a href='/list-review/<?php echo $product->getId() ?>'>(<?php echo $nReviews ?>)</a>
            <div class="look">
                <a>Ver más</a>
            </div>
        </div>
        <?php
    }
} else {
    echo $new['error'];
}
?>
</div>
<script>
    window.onload = () => {
        const ctrlBack = document.querySelectorAll('[id*=ctrl-bck]');
        const ctrlForward = document.querySelectorAll('[id*=ctrl-frw]');
        ctrlBack.forEach((control) => {
            control.addEventListener('click', (e) => {
                e.preventDefault();
                back(control);
            });
        });
        ctrlForward.forEach((control) => {
            control.addEventListener('click', (e) => {
                e.preventDefault();
                next(control);
            });
        });
        function back(elem) {
            const id = elem.id.split('-').pop();
            const slides = document.getElementById('track-'+id).children
            const minOffset = 0;
            for(let i=0;i < slides.length;i++) {
                let position = parseInt(slides[i].style.left.replace('%',''))+100;
                if (i === 0 && position > minOffset) break;
                slides[i].style.left = position+'%';
            }
        }
        function next(elem) {
            const id = elem.id.split('-').pop();
            const slides = document.getElementById('track-'+id).children
            const maxOffset = (slides.length * 100 - 100)*(-1);
            for(let i=0;i < slides.length;i++) {
                let position = parseInt(slides[i].style.left.replace('%',''))-100;
                if (position < maxOffset) break;
                slides[i].style.left = position+'%';
            }
        }
    }
</script>
<?php include __DIR__ . '/footer.phtml' ?>