<!--------------------------------------------
-- Plantilla HTML para la pagina de portada --
--------------------------------------------->
<?php /* incluimos la plantilla goblal */ include __DIR__ . '/layout.phtml' ?>
<?php /* incluimos la cabecera */ include __DIR__ . '/header.phtml' ?>

<h1>Valoraciones</h1>

<div><?php echo $product->getName() ?></div>

<?php var_dump($reviews) ?>

<?php /* incluimos el footer */ include __DIR__ . '/footer.phtml' ?>