<!--------------------------------------------
-- Plantilla HTML para la pagina de portada --
--------------------------------------------->
<?php include __DIR__ . '/layout.phtml' ?>
<?php include __DIR__ . '/header.phtml' ?>

<h2 class="list-title"><i class="material-icons">stars</i>Productos de la categoría</h2>
<div class="list list-review">
<?php if (count($products) > 0 && !isset($products['error'])) {
    // Iterar sobre los productos para listarlos
    foreach ($products as $product) {
        if ($product->getNReviews() == 0) {
            $nReviews = 'Sin valoraciones';
        } elseif ($product->getNReviews() == 1) {
            $nReviews = $product->getNReviews(). ' valoración';
        } else {
            $nReviews = $product->getNReviews(). ' valoraciones';
        }
        ?>
        <div class='item'>
            <div class='carousel'>
                <?php if (count($product->getImg()) > 1) {
                    echo "<div class='carousel__controls reverse' id='ctrl-bck-{$product->getId()}'></div >
              <div class='carousel__controls' id='ctrl-frw-{$product->getId()}'></div >";
                } ?>
                <ul class='carousel__track' id="track-<?php echo $product->getId() ?>">
                    <?php foreach ($product->getImg() as $key => $img) {
                        $percent = $key * 100;
                        echo "<li class='carousel__slide' style='left: $percent%'>
                <img src='/public/img/products/{$product->getId()}/$img' height='50%' width='100%' alt='Imagen del producto'/>
              </li>";
                    }
                    ?>
                </ul>
            </div>
            <h3 title="<?php echo $product->getName() ?>"><?php echo $product->getName() ?></h3>
            <a class="rating-link" href='/add-review/<?php echo$product->getId() ?>'>
                <div class="rating" title="Hacer una valoración">
                    <span><?php echo round($product->getPoints(),1) ?></span>
                    <i class='material-icons'>star</i>
                </div>
            </a>
            <a href='/add-review/<?php echo $product->getId() ?>#reviews'>(<?php echo $nReviews ?>)</a>
            <div class="look">
                <a href="/product/<?php echo $product->getId() ?>">Ver más</a>
            </div>
        </div>
        <?php
    }
} else {
    echo "<div class='error'>{$products['error']}</div>";
}
?>
</div>

<?php include __DIR__ . '/footer.phtml' ?>