<!--------------------------------------------
-- Plantilla HTML para la pagina de portada --
--------------------------------------------->
<?php /* incluimos la plantilla goblal */
include __DIR__ . '/layout.phtml' ?>
<?php /* incluimos la cabecera */
include __DIR__ . '/header.phtml' ?>

<h1>Inicio de sesión</h1>

<form action="login" method="post">
    <?php
    if (isset($_SESSION['error'])) {
        echo "<div>{$_SESSION['error']}</div>";
        unset($_SESSION['error']);
    }
    ?>
    <input type="text" name="username" placeholder="Nombre de usuario" value="<?php if (isset($username)) echo $username ?>"/>
    <input type="password" name="password" placeholder="Contrasela"/>
    <button>Entrar</button>
</form>


<?php /* incluimos el footer */
include __DIR__ . '/footer.phtml' ?>