<?php include __DIR__ . '/layout.phtml' ?>
<?php include __DIR__ . '/header.phtml' ?>

<div class="main-box">
    <div class="wrapper">
        <form action="/login" method="post">
            <h2 class="form-title">Iniciar sesión</h2>
            <?php
            if (isset($_SESSION['error'])) {
                echo "<div>{$_SESSION['error']}</div>";
                unset($_SESSION['error']);
            }
            ?>
            <div class="form-group">
                <input type="text" id="username" name="username" value="<?php if (isset($username)) echo $username ?>" required>
                <label for="username">Nombre y apellidos</label>
            </div>
            <div class="form-group">
                <input type="password" id="password" name="password" required>
                <label for="password">Contraseña</label>
            </div>
            <button class="btn">Entrar</button>
        </form>
        <div class="aside-form">
            <p>¿No tienes cuenta?</p>
            <a class="btn btn-light">Registrarse</a>
        </div>
    </div>
</div>

<?php /* incluimos el footer */
include __DIR__ . '/footer.phtml' ?>