<?php include __DIR__ . '/layout.phtml' ?>
<?php include __DIR__ . '/header.phtml' ?>

<?php
    switch ($user->getRol()) {
        case 1:
            $rol = 'Admin';
            break;
        case 2:
            $rol = 'Novato';
            break;
        case 3:
            $rol = 'Intermedio';
            break;
        case 4:
            $rol = 'Experto';
    }
?>

<main class="list column">
    <h2 class="list-title admin-title" style="margin: 0 auto; padding: 24px; box-sizing: border-box; width: 50%"><i class="material-icons">account_circle</i>Información de usuario</h2>
    <form class="edit" action='/admin/edit-user/' method='post' name="addProduct" enctype='multipart/form-data' style="margin: 16px auto">
        <input type="hidden" name="id" value="<?php echo $user->getId() ?>">
        <?php
        if (isset($_SESSION['error-modify'])) {
            echo "<div class='error'>{$_SESSION['error-modify']}</div>";
            unset($_SESSION['error-modify']);
        }
        ?>
        <div class="form-group">
            <input type='text' id="name" name='name' value="<?php echo $user->getName() ?>" required>
            <label for="name">Nombre y apellidos</label>
        </div>
        <div class="form-group">
            <input type='text' id="email" name='email' value="<?php echo $user->getEmail() ?>" required>
            <label for="email">Correo electrónico</label>
        </div>
        <div class="form-group">
            <input type='text' id="profile" name='profile' value="<?php echo $rol ?>" readonly required>
            <label class="filled" for="profile">Perfil</label>
        </div>
        <button class="btn" type='submit'>Editar</button>
    </form>

    <h2 class="list-title admin-title" style="margin: 0 auto; padding: 24px; box-sizing: border-box; width: 50%"><i class="material-icons">lock</i>Cambiar contraseña</h2>
    <form class="edit" action='/admin/edit-password/' method='post' name="addProduct" enctype='multipart/form-data' style="margin: 16px auto">
        <input type="hidden" name="id" value="<?php echo $user->getId() ?>">
        <?php
        if (isset($_SESSION['error-pass'])) {
            echo "<div class='error'>{$_SESSION['error-pass']}</div>";
            unset($_SESSION['error-pass']);
        }
        ?>
        <div class="form-group">
            <input type='password' id="old" name='old' required>
            <label for="old">Contraseña actual</label>
        </div>
        <div class="form-group">
            <input type='password' id="new" name='new' required>
            <label for="new">Nueva contraseña</label>
        </div>
        <div class="form-group">
            <input type='password' id="verify" name='verify' required>
            <label for="verify">Verificar nueva contraseña</label>
        </div>
        <button class="btn" type='submit'>Cambiar</button>
    </form>
</main>
<?php include __DIR__ . '/footer.phtml' ?>