<?php include __DIR__ . '/../layout.phtml' ?>
<?php include __DIR__ . '/header.phtml' ?>

<main class="list">
<ul class="category-list">
    <h4>Categorías actuales</h4>
<?php
if (isset($categories) && !isset($categories['error'])) {
    foreach ($categories as $category) {
        $parent = $category['parentInfo'];
        $childs = $category['childs'];
        echo "<li class='parent'>
                  <span>{$parent->getName()}</span>
                  <div class='btn-box'>
                      <i class='material-icons'>edit</i>
                      <i class='material-icons'>delete</i>
                  </div>
              </li>";
        echo "<ul class='child'>";
        foreach ($childs as $child) {
            echo "<li>
                      <span>{$child->getName()}</span>
                      <div class='btn-box'>
                          <i class='material-icons'>edit</i>
                          <i class='material-icons'>delete</i>
                      </div>
                  </li>";
        }
        echo "</ul>";
    }
} elseif (isset($categories['error'])) {
    echo "<div>{$categories['error']}</div>";
}
?>
</ul>

<form class="edit" action="" method="post">
    <h4>Añadir categoría</h4>
<?php
if (isset($categories) && !isset($categories['error'])) {
    echo "<div class='form-group'>
              <select id='parent' name='parent'>
                  <option value='0'>Categoría padre (opcional)</option>";
    foreach ($categories as $category) {
        $parent = $category['parentInfo'];
        echo "<option value='{$parent->getId()}'>{$parent->getName()}</option>";
    }
    echo "    </select>
          </div>";
}
?>
    <div class="form-group">
        <input type="text" id="name" name="name" required>
        <label for="name">Nombre de categoría</label>
    </div>
    <button class="btn" type="submit">Añadir</button>
<?php
    if (isset($_SESSION['add-error'])) {
        echo "<div>{$_SESSION['add-error']}</div>";
        unset($_SESSION['add-error']);
    }
?>
</form>
</main>
<script>
    window.onload = () => {
        let parents = document.querySelectorAll('.parent');
        parents.forEach((parent) => {
           parent.addEventListener('click', () => {
               let childs = parent.nextSibling;
               childs.classList.toggle('active');
           })
        });
    }
</script>
<?php include __DIR__ . '/../footer.phtml' ?>