<!--------------------------------------------
-- Plantilla HTML para la pagina de portada --
--------------------------------------------->
<?php /* incluimos la plantilla goblal */ include __DIR__ . '/../layout.phtml' ?>
<?php /* incluimos la cabecera */ include __DIR__ . '/../header.phtml' ?>

<h1>Categorías</h1>

<ul>
    <h4>Lista de categorías creadas</h4>
<?php
if (isset($categories) && !isset($categories['error'])) {
    foreach ($categories as $category) {
        $parent = $category['parentInfo'];
        $childs = $category['childs'];
        echo "<li>{$parent->getName()} (id: {$parent->getId()})</li>";
        echo "<ul>";
        foreach ($childs as $child) {
            echo "<li>{$child->getName()} (id: {$child->getId()})</li>";
        }
        echo "</ul>";
    }
    echo "<br><div>Para modificar una categoría se usará AJAX. ";
    echo "Para esta prueba pueden usarse las siguientes urls:</div>";
    echo "<div>Modificar: /admin/edit-category/{id}/{name}[/{parent_id}] &nbsp;&nbsp;&nbsp;";
    echo "Ejemplo: /admin/edit-category/1/Nuevo Nombre</div>";
    echo "<div>Eliminar: /admin/delete-category/{id} &nbsp;&nbsp;&nbsp;";
    echo "Ejemplo: /admin/delete-category/1</div>";
} elseif (isset($categories['error'])) {
    echo "<div>{$categories['error']}</div>";
}
?>
</ul>

<form action="" method="post">
    <h4>Añadir categoría</h4>
<?php
if (isset($categories) && !isset($categories['error'])) {
    echo "<select name='parent'>";
    echo "<option value='0'>Seleccionar padre</option>";
    foreach ($categories as $category) {
        $parent = $category['parentInfo'];
        echo "<option value='{$parent->getId()}'>{$parent->getName()}</option>";
    }
    echo "</select>";
}
?>
    <input type="text" name="name" placeholder="Nombre de categoría">
    <button type="submit">Añadir</button>
<?php
    if (isset($_SESSION['add-error'])) {
        echo "<div>{$_SESSION['add-error']}</div>";
    }
?>
</form>

<?php /* incluimos el footer */ include __DIR__ . '/../footer.phtml' ?>