<?php include __DIR__ . '/../layout.phtml' ?>
<?php include __DIR__ . '/header.phtml' ?>

<h2 class="list-title"><i class="material-icons">dashboard</i>Productos</h2>
<main class="list column">
    <div class="list title row">
        <div>Nombre</div>
        <div>Categoría</div>
        <div>Valoraciones</div>
        <div>Promedio</div>
        <div></div>
    </div>
<?php if (count($products) > 0 && !isset($products['error'])) {
    foreach ($products as $product) {
        echo "<div class='list row product'>
                  <div>{$product->getName()}</div>
                  <div>{$product->getCategory()}</div>
                  <div>{$product->getNReviews()}</div>
                  <div>{$product->getPoints()}</div>
                  <div>
                    <a href='#'><!--
                        --><i class='material-icons'>edit</i><!--       
                 --></a>
                    <a href='#' style='background-color: #ff1744'>
                        <i class='material-icons'>delete</i>
                    </a>
                  </div>
              </div>";
    }
}
?>
</main>




<?php include __DIR__ . '/../footer.phtml' ?>