<!--------------------------------------------
-- Plantilla HTML para la pagina de portada --
--------------------------------------------->
<?php /* incluimos la plantilla goblal */ include __DIR__ . '/../layout.phtml' ?>
<?php /* incluimos la cabecera */ include __DIR__ . '/../header.phtml' ?>

<h1>Admin Panel</h1>

<a href="categories">Añadir Categoría</a><br>
<a href="products">Añadir Producto</a>

<?php /* incluimos el footer */ include __DIR__ . '/../footer.phtml' ?>