<?php include __DIR__ . '/../layout.phtml' ?>
<?php include __DIR__ . '/header.phtml' ?>

<main class="list column">
<h2 class="list-title admin-title" style="margin: auto; padding: 24px; box-sizing: border-box; width: 50%"><i class="material-icons">category</i>Añadir producto</h2>
<?php
if (isset($categories) && !isset($categories['error'])) {
    if (isset($_SESSION['args'])) {
        $name = $_SESSION['args']['name'];
        $description = $_SESSION['args']['description'];
        $details = $_SESSION['args']['details'];
        $categorySelected = $_SESSION['args']['category'];
        unset($_SESSION['args']);
    }
?>
    <form class="edit" action='' method='post' name="addProduct" enctype='multipart/form-data' style="margin: auto">
        <div class="form-group">
            <input type='text' id="name" name='name' value="<?php if (isset($name)) echo $name ?>" required>
            <label for="name">Nombre del producto</label>
        </div>
        <div class="form-group">
            <select name='category'>
                <option value="0">Elegir categoría</option>
                <?php
                foreach ($categories as $category) {
                    $parent = $category['parentInfo'];
                    $childs = $category['childs'];
                    echo "<option value='{$parent->getId()}'>{$parent->getName()}</option>";
                    foreach ($childs as $child) {
                        echo "<option value='{$child->getId()}'>&nbsp;&nbsp;&nbsp;{$child->getName()}</option>";
                    }
                }
                ?>
            </select>
        </div>
        <div class="form-group">
            <textarea id="description" name='description' required><?php if (isset($description)) echo $description ?></textarea>
            <label for="description">Descripción del producto</label>
        </div>
        <div class="form-group">
            <textarea id="details" name='details'><?php if (isset($details)) echo $details ?></textarea>
            <label for="details">Detalle del producto (opcional)</label>
        </div>
        <div class="form-group">
            <input type='file' id="img" name='img[]' accept="image/*" multiple>
            <label for="img">Imágenes (Min. 1)</label>
        </div>
        <div id="imgs"></div>
        <button class="btn" type='submit'>Añadir</button>
<?php
    if (isset($_SESSION['add-error'])) {
        echo "<div>{$_SESSION['add-error']}</div>";
        unset($_SESSION['add-error']);
    }
?>
    </form>
<?php
} else {
    echo "<div>Debe añadir categorías antes de agregar productos</div>";
}
?>
</main>
<script>
    window.onload = () => {
        let input = document.querySelector('input[type="file"]');
        input.addEventListener('change', (e) => {
            let imgsDiv = document.getElementById('imgs');
            imgsDiv.innerHTML = "";
            let files = input.files;
            for (let i = 0; i < files.length; i++) {
                let reader  = new FileReader();
                reader.onload = (e) => {
                    let image = document.createElement("img");
                    image.src = e.target.result;
                    image.width = "100";
                    image.height = "100";
                    imgsDiv.appendChild(image);
                }
                console.log(files[i] instanceof File);
                reader.readAsDataURL(files[i]);
            }
        })
    }
</script>

<?php include __DIR__ . '/../footer.phtml' ?>