<!--------------------------------------------
-- Plantilla HTML para la pagina de portada --
--------------------------------------------->
<?php /* incluimos la plantilla goblal */ include __DIR__ . '/../layout.phtml' ?>
<?php /* incluimos la cabecera */ include __DIR__ . '/../header.phtml' ?>

<h1>Productos</h1>

<ul>
    <h4>Lista de productos</h4>
<?php
if (isset($products) && !isset($products['error'])) {
    foreach ($products as $product) {
        var_dump($product);
    }
} elseif (isset($products['error'])) {
    echo "<div>{$products['error']}</div>";
}
?>
</ul>

<form action="" method="post">
    <h4>Añadir producto</h4>
    <input type="text" name="name" placeholder="Nombre del producto">
    <textarea name="description">Descripción del producto</textarea>
    <textarea name="details">Detalle del producto (opcional)</textarea>
    <input type="file" name="img" multiple>
    <select>
<?php
if (isset($categories) && !isset($categories['error'])) {
    foreach ($categories as $category) {
        var_dump($category);
//        echo "<option value='{$category->getId()}'>{$category->getName()}</option>";
    }
}
?>
    </select>
    <button type="submit">Añadir</button>
<?php
    if (isset($_SESSION['add-error'])) {
        echo "<div>{$_SESSION['add-error']}</div>";
        unset($_SESSION['add-error']);
    }
?>
</form>

<?php /* incluimos el footer */ include __DIR__ . '/../footer.phtml' ?>