<!--------------------------------------------
-- Plantilla HTML para la pagina de portada --
--------------------------------------------->
<?php /* incluimos la plantilla goblal */ include __DIR__ . '/../layout.phtml' ?>
<?php /* incluimos la cabecera */ include __DIR__ . '/../header.phtml' ?>

<h1>Productos</h1>

<ul>
    <h4>Lista de productos</h4>
<?php
if (isset($products) && !isset($products['error'])) {
    foreach ($products as $product) {
        var_dump($product);
    }
} elseif (isset($products['error'])) {
    echo "<div>{$products['error']}</div>";
}
?>
</ul>
<?php
if (isset($categories) && !isset($categories['error'])) {
    if (isset($_SESSION['args'])) {
        $name = $_SESSION['args']['name'];
        $description = $_SESSION['args']['description'];
        $details = $_SESSION['args']['details'];
        $categorySelected = $_SESSION['args']['category'];
        unset($_SESSION['args']);
    }
?>
    <form action='' method='post' enctype='multipart/form-data'>
        <h4>Añadir producto</h4>
        <input type='text' name='name' placeholder='Nombre del producto' value="<?php if (isset($name)) echo $name ?>">
        <textarea name='description' placeholder='Descripción del producto'><?php if (isset($description)) echo $description ?></textarea>
        <textarea name='details' placeholder='Detalle del producto (opcional)'><?php if (isset($details)) echo $details ?></textarea>
        <input type='file' name='img[]' multiple>
        <select name='category'>
<?php
    foreach ($categories as $category) {
        $parent = $category['parentInfo'];
        $childs = $category['childs'];
        echo "<option value='{$parent->getId()}'>{$parent->getName()}</option>";
        foreach ($childs as $child) {
            echo "<option value='{$child->getId()}'>&nbsp;&nbsp;&nbsp;{$child->getName()}</option>";
        }
    }
?>
        </select>
        <button type='submit'>Añadir</button>
<?php
    if (isset($_SESSION['add-error'])) {
        echo "<div>{$_SESSION['add-error']}</div>";
        unset($_SESSION['add-error']);
    }
?>
    </form>
<?php
} else {
    echo "<div>Debe añadir categorías antes de agregar productos</div>";
}
?>

<?php /* incluimos el footer */ include __DIR__ . '/../footer.phtml' ?>