<!--------------------------------------------
-- Plantilla HTML para la pagina de portada --
--------------------------------------------->
<?php /* incluimos la plantilla goblal */ include __DIR__ . '/../layout.phtml' ?>
<?php /* incluimos la cabecera */ include __DIR__ . '/../header.phtml' ?>

<h1>Valoraciones</h1>

<form action="" method="post">
    <h4>Añadir valoracion</h4>
    <select name="points">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
    </select>
    <textarea name="comment">Comentario del producto</textarea>

    <button type="submit">Añadir</button>

<?php
    if (isset($_SESSION['add-error'])) {
        echo "<div>{$_SESSION['add-error']}</div>";
        unset($_SESSION['add-error']);
    }
?>
</form>

<?php /* incluimos el footer */ include __DIR__ . '/../footer.phtml' ?>