<?php include __DIR__ . '/../layout.phtml' ?>
<?php include __DIR__ . '/header.phtml' ?>

<h2 class="list-title"><i class="material-icons">dashboard</i>Moderar valoraciones</h2>
<main class="list column">
    <div class="list title row">
        <div>Usuario</div>
        <div>Creación</div>
        <div>Producto</div>
        <div>Puntuación</div>
        <div></div>
    </div>
    <div id="msg"></div>
<?php
if (isset($_SESSION['success'])) {
    echo "<div class='success'>{$_SESSION['success']}</div>";
    unset($_SESSION['success']);
}
if (count($reviews) > 0 && !isset($reviews['error'])) {
    foreach ($reviews as $review) {
        $points = round($review->getPoints(), 1);
        echo "<div class='list row product' id='{$review->getId()}'>
              <div style='text-align: center'>{$review->getUsername()}</div>
              <div>{$review->getDateCreated()}</div>
              <div>{$review->getProduct()}</div>
              <div>$points</div>
              <div>
                <a href='/admin/review/{$review->getId()}'><!--
                    --><i class='material-icons'>remove_red_eye</i><!--       
             --></a>
              </div>
          </div>";
    }
} else {
    if (isset($reviews['error']))
        echo "<div class='list row title'>{$reviews['error']}</div>";
}
?>

<?php include __DIR__ . '/../footer.phtml' ?>